name: Build on push

on: push

# Set the GITHUB_TOKEN to a restricted permission we don't need anything else than this.
# This will disable all other permissions than metadata: read, which is always enabled.
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    strategy:
      matrix:
        otp: [25, 26]
        elixir: [1.15.x, 1.16.x, 1.17.x]
    env:
      MIX_ENV: test
      cache_version: v4

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - Uses: erlef/setup-elixir@v1
        name: Setup elixir
        id: setup-beam
        with:
          version-type: strict
          version-file: .tool-versions

      - uses: actions/cache@v1
        name: Cache deps
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}

      - uses: actions/cache@v4
        name: Cache deps
        with:
          path: |
            deps
            _build
          key: >
            mix-${{ env.cache_version }}-${{ runner.os }}-
            ${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: >
            mix-${{ env.cache_version }}-${{ runner.os }}-
            ${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}

      - name: Install dependencies
        run: mix deps.get

      - name: Build
        run: mix compile

      - name: Test
        run: mix test --include skip

      - name: Credo
        run: mix credo

      - name: Dialyzer
        run: mix dialyzer

      - name: Check if files is formatted
        run: mix format --check-formatted

      - name: Check that no unused deps exist
        run: |
          mix deps.clean --unused --unlock
          git diff --exit-code
