name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    strategy:
      matrix:
        otp: [22.1.8.1, 22.2.8, 22.3.2]
        elixir: [1.9.4, 1.10.2]
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/cache@v1
        name: Cache deps
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - uses: actions/cache@v1
        name: Cache _build
        with:
          path: _build
          key: build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - uses: actions/setup-elixir@v1
        name: Setup elixir
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - run: mix deps.get
      - run: mix compile
      - run: mix test --trace
      - run: mix credo
      - run: mix dialyzer
      - run: mix format --check-formatted
