name: CI

on: push

# Set the GITHUB_TOKEN to a restricted permission we don't need anything else than this.
# This will disable all other permissions than metadata: read, which is always enabled.
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    strategy:
      matrix:
        otp: ["24.1.7", "24.2.2", "24.3.2"]
        elixir: ["1.12.3", "1.13.4"]
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/cache@v1
        name: Cache deps
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - uses: actions/cache@v1
        name: Cache _build
        with:
          path: _build
          key: build-erlef-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            build-erlef-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - uses: erlef/setup-elixir@v1
        name: Setup elixir
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - run: mix deps.get

      - name: Check that no unused deps exist
        run: |
          mix deps.clean --unused --unlock
          git diff --exit-code

      - run: mix compile
      - run: mix test --trace --include skip
      - run: mix credo
      - run: mix dialyzer
      - run: mix format --check-formatted
